let right = new Image();
let left = new Image();
let up = new Image();
let down = new Image();

right.src = './sprites/arrow_right_note.png';
left.src = './sprites/arrow_left_note.png';
up.src = './sprites/arrow_up_note.png';
down.src = './sprites/arrow_down_note.png';

let song1 = [
    null, null, null, null,
    null, null, null, null,
    null, null, null, null,
    null, null, null, null,
    [left], null, [right], null,
    [down], null, [up], null,
    [right], null, [left], null,
    [up], null, [down], null,
    [left], null, [up], null,
    [down], null, [right], null,
    [left], null, [down], null,
    [right], null, [up], null,
    [right], null, [down], null,
    [up], null, [left], null,
    [right], null, [up], null,
    [left], null, [down], null,
    [left], null, [down], null,
    [up], null, [right], null,
    [up], null, [down], null,
    [left], null, null, [right],
    [down], null, [up], null,
    [right], null, [left], null,
    [right], null, [up], null,
    [down], null, null, [up],
    [right], null, [up], null,
    [down], null, [left], null,
    [down], null, [up], null,
    [right], null, null, [left],
    [up], null, [right], null,
    [left], null, [down], null,
    [left], null, [right], null,
    [up], null, null, [down],
    [left, right], null, [left], [right],
    [up], [down], [up], [down],
    [right], null, [left], null,
    [right], [left], [down], [up],
    [left, right], null, [right], [down],
    [left], [up], [left], [up],
    [down], null, [right], null,
    [down], [right], [up], [left],
    [up], null, [down], null,
    [left], [up, down], [right], [up, down],
    [down], null, [up], null,
    [right], [up, down], [left], [up, down],
    [right], null, [left], null,
    [down], [left, right], [up], [left, right],
    [left], null, [right], null,
    [left, right], null, null, null,
    [left], null, [right], null,
    [down], null, [up], null,
    [down], null, [right], null,
    [left], null, null, [right],
    [down], null, [up], null,
    [right], null, [left], null,
    [right], null, [up], null,
    [down], null, null, [up],
    [right], [down], [up], [left],
    [right], [up], [left], [down],
    [left], [up], [down], [right],
    [left], [down], [right], [up],
    [right], [up], [down], [left],
    [right], [left], [up], [down],
    [left], [down], [up], [right],
    [left], [right], [down], [left, right]
];

let song2 = [
    null, null, null, null,
    null, null, null, null,
    null, null, null, null,
    null, null, null, null,
    [up], null, null, null,
    [down], null, null, null,
    [up], null, null, null,
    [down], null, null, null,
    [right], null, [right], null,
    [down], null, [down], null,
    [right], null, [right], null,
    [left], null, [left], null,
    [right], [right], [right], null,
    [left], [left], [left], null,
    [right], null, [left], null,
    [left, right], null, null, null,
    [up], null, [down], null,
    [up], null, [down], null,
    [up], null, [down], null,
    [up], [up], [down], [down],
    [up], [down], [up], null,
    [down], null, [down], null,
    [right], null, null, null,
    [left], null, [left], null,
    [down], null, null, null,
    [left], null, [left], null,
    [up], null, null, null,
    [down], null, [down], null,
    [left, right], null, null, null,
    [up], null, null, null,
    [up], [up], [up], null,
    [down], null, null, null,
    [down], [down], [down], null,
    [right], null, null, null,
    [right], [right], [right], null,
    [left], null, [left], null,
    [left], [left], [left], null,
    [up], null, null, null,
    [left], null, null, null,
    [left], null, null, null,
    [right], null, null, null,
    [down], null, null, null,
    [right], null, null, null,
    [left], null, [right], null,
    [left, right], null, null, null,
    [right], null, [right], null,
    [right], null, [down], [down],
    [down], null, [down], null,
    [down], null, [up], [up],
    [up], null, [up], null,
    [up], null, [left], [left],
    [left], null, [left], null,
    [left], null, null, null,
    [right], [right], [right], null,
    [left], null, [left], null,
    [up], [up], [up], null,
    [down], null, [down], null,
    [up], [up], [up], null,
    [down], [down], [down], null,
    [up], null, [down], null,
    [up, down], null, null, null,
    [left], null, null, null
];

let song3 = [
    [], [], [], [],
    [], [], [], [],
    [up], [up], [up], [],
    [down], [up], [down], [],
    [left], [], [up], [],
    [right], [down], [up], [],
    [up], [up], [up], [],
    [down], [down], [down], [],
    [left], [up], [left], [],
    [up], [down], [up], [],
    [right], [], [up], [],
    [down], [], [up], [],
    [left], [up], [up], [],
    [down], [up], [up], [],
    [right], [], [down], [],
    [up], [], [left], [],
    [up], [down], [down], [],
    [right], [left], [left], [],
    [right, left], [], [], [],
    [], [up], [down], [], 
    [up], [], [up], [],
    [down], [down], [down], [],
    [left], [], [left], [],
    [right], [up], [left, right], [left, up],
    [], [up], [], [up],
    [], [down], [down], [down],
    [], [left], [], [left],
    [right], [up], [down], [],
    [up], [down], [up], [left],
    [up], [down], [up], [],
    [right], [down], [up], [down],
    [left], [down], [up], [left, right],
    [], [up], [down], [up],
    [left], [up], [right], [],
    [up], [down], [up], [left, right],
    [up, down], [], [], [],
    [up], [], [down], [],
    [up], [up], [down], [],
    [left], [right], [up, down], [], 
    [right], [left], [up, down], [],
    [right], [], [up], [],
    [left], [down], [left], [],
    [right], [up], [down], [up],
    [down], [up], [left, right], [],
    [up], [], [down], [],
    [up], [down], [left], [down],
    [up], [up], [left, right], [],
    [down], [down], [left, right], [],
    [up], [], [down], [],
    [right], [up], [down], [up],
    [down], [left, right], [up, down], [],
    [up], [up], [down], [],
    [up], [], [down], [],
    [up], [right], [up], [down],
    [up], [up], [left, right], [],
    [down], [down], [left, right], [],
    [up], [], [down], [],
    [up], [left], [right], [up], 
    [up], [up], [left, right], [],
    [down], [down], [up], null,
    [down], [down], [down], [up],
    [down], [down], [down], null,
    [right], [right], [right], [left],
    [right], [right], [right], null,
    [down], [down], [down], [up],
    [down], [down], [down], null,
    [left], [left], [left], [up],
    [left], [left], [left], null,
    [left, right], null, null, null,
    null, null, null, null,
    [up, down], null, [left, right], null,
    [up], [down], [up], [left],
    [up], null, [down], null,
    [right], [up], down, null,
    [up], null, [left], null,
    [up], [down], [up], null,
    [right], [right], [right], [right],
    [left], [left], [right], null,
    [up], [up], [up], [down],
    [up], [left], [up], null,
    [right], [right], [right], [down],
    [up], [left], [up], null,
    [up], [up], [up], [down],
    [up], [left], [up], [left],
    [up], [left], [up], [right, left]
]

export function getSong(songNum) {
    switch (songNum) {
		case 1:
            return song1;
        case 2:
            return song2;
        case 3:
            return song3;
	}
}